name: slugify
version: 0.2.0
description: Converts strings into slugs, for pretty URLs
author: izolate
homepage: https://github.com/izolate/slugify
sdk: ">=2.0.0-dev <3.0.0"
dev_dependencies:
  test: ^1.5.1